### ISSUE TITLE
Cannot zoom in or out after map loads

### ISSUE THREAD

**Issue by skaltman** [rstudio/leaflet.mapboxgl#1]
@jcheng5 @mikelmaron @mourner

We want to render a custom Mapbox style using `addMapboxGL()`. Here's my code:

```
library(leaflet)
library(leaflet.mapboxgl)

leaflet() %>% 
  addMapboxGL(
    style = "mapbox://styles/sarakai24/cjsnsfr4o6qeg1fqgp63ilzjj"
  )
```
Upon loading, you cannot zoom the map out. If you zoom in, the map jumps to the lowest zoom level.

Once the map has jumped to the lowest zoom level, you can zoom in and out.

**Comment by jcheng5** [comment]
I'm not sure why this is happening, but adding an explicit `setView` (or, I assume, `fitBounds`) seems to work around it:

```r
library(leaflet)
library(leaflet.mapboxgl)

leaflet() %>% 
  addMapboxGL(
    style = "mapbox://styles/sarakai24/cjsnsfr4o6qeg1fqgp63ilzjj"
  ) %>% 
  setView(
    lng = -0.1278, lat = 51.5074, zoom = 14
  )
```

**Comment by jcheng5** [comment]
@skaltman If you reinstall and try again, this should work now. If not, feel free to reopen the issue.

Mapbox GL JS has a feature where if you don't specify the center/zoom of the map, it automatically zooms to the center/zoom that's specified in the style (your style had such a center/zoom, the ones I tested with were generic maps and did not). However, there seems to be a minor bug in that Mapbox GL JS doesn't know the difference between the center/zoom not being specified, and the center/zoom being specified the same as the default values (lat: 0, lng: 0, zoom: 0).

So basically, when you create an R leaflet map and don't put any shapes on it, we default to 0/0/0. The Mapbox GL Leaflet plugin passes that explicitly to Mapbox GL JS. That leaves us in a situation where the Leaflet map thinks it's at 0/0/0, and the Mapbox GL layer thinks it's somewhere else. That's why you couldn't zoom out; because those zoom controls belong to Leaflet. And when you zoomed in, that caused the Mapbox GL layer to sync up with the center/zoom used by Leaflet.

I fixed this in two ways. First, `addMapboxGL` now has a `setView` parameter that defaults to `TRUE`. This causes Leaflet to follow Mapbox's lead, and centers/zooms the entire Leaflet map to match the Mapbox layer. Second, even if you `setView=FALSE`, I now force the Mapbox layer to sync with Leaflet after it loads.

@mikelmaron I didn't find an easy fix for this issue in Mapbox GL JS, and it only really becomes problematic when used with the Mapbox GL Leaflet plugin. I did try patching leaflet-mapbox-gl.js to never pass 0 lat/lng/zoom to Mapbox GL, but instead, if it was about to, it'd change the latitude to 0.00000001 or whatever. That worked just fine, but obviously, is a bit hacky.

**Comment by skaltman** [comment]
This works great, thanks!

**Comment by mikelmaron** [comment]
Glad you found a workaround @skaltman. I'm not sure if there is an issue or not to address in Mapbox GL JS.

@mourner what's your take on the mix up between "default" and 0/0/0 in Mapbox GL JS

> However, there seems to be a minor bug in that Mapbox GL JS doesn't know the difference between the center/zoom not being specified, and the center/zoom being specified the same as the default values (lat: 0, lng: 0, zoom: 0)
